#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# PIDs for cleanup
ANVIL_PID=""
VRF_WATCHER_PID=""
NEXT_PID=""

cleanup() {
    echo -e "\n${YELLOW}Shutting down local environment...${NC}"

    if [ -n "$NEXT_PID" ]; then
        kill $NEXT_PID 2>/dev/null || true
    fi

    if [ -n "$VRF_WATCHER_PID" ]; then
        kill $VRF_WATCHER_PID 2>/dev/null || true
    fi

    if [ -n "$ANVIL_PID" ]; then
        kill $ANVIL_PID 2>/dev/null || true
    fi

    # Clean up .env.local if it was created for local dev
    if [ -f "apps/web/.env.local" ] && grep -q "NEXT_PUBLIC_CHAIN=local" "apps/web/.env.local" 2>/dev/null; then
        rm -f apps/web/.env.local
        echo -e "${GREEN}Cleaned up .env.local${NC}"
    fi

    echo -e "${GREEN}Shutdown complete${NC}"
    exit 0
}

trap cleanup EXIT INT TERM

# Get the project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${GREEN}Starting local development environment...${NC}"
echo ""

# 1. Start Anvil
echo -e "${YELLOW}Starting Anvil...${NC}"
anvil --block-time 2 > /tmp/anvil.log 2>&1 &
ANVIL_PID=$!

# Wait for Anvil to be ready
sleep 2
if ! kill -0 $ANVIL_PID 2>/dev/null; then
    echo -e "${RED}Failed to start Anvil${NC}"
    cat /tmp/anvil.log
    exit 1
fi
echo -e "${GREEN}Anvil started (PID: $ANVIL_PID)${NC}"

# 2. Deploy contracts
echo -e "\n${YELLOW}Deploying contracts...${NC}"
cd contracts

DEPLOY_OUTPUT=$(forge script script/DeployLocal.s.sol:DeployLocal \
    --rpc-url http://localhost:8545 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    --broadcast 2>&1) || {
    echo -e "${RED}Deployment failed:${NC}"
    echo "$DEPLOY_OUTPUT"
    exit 1
}

# Extract addresses from deployment output
VRF_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "VRF_COORDINATOR=" | sed 's/.*VRF_COORDINATOR=//')
CONTEST_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "FIRST_BLOOD_CONTEST=" | sed 's/.*FIRST_BLOOD_CONTEST=//')
CONTEST_ID=$(echo "$DEPLOY_OUTPUT" | grep "CONTEST_ID=" | sed 's/.*CONTEST_ID=//')

if [ -z "$VRF_ADDRESS" ] || [ -z "$CONTEST_ADDRESS" ]; then
    echo -e "${RED}Failed to extract addresses from deployment output${NC}"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

echo -e "${GREEN}Contracts deployed:${NC}"
echo "  VRF Coordinator: $VRF_ADDRESS"
echo "  FirstBloodContest: $CONTEST_ADDRESS"
echo "  Contest ID: $CONTEST_ID"

cd "$PROJECT_ROOT"

# 3. Write .env.local for the frontend
echo -e "\n${YELLOW}Configuring frontend...${NC}"
cat > apps/web/.env.local << EOL
# Generated by dev-local.sh - do not edit manually
NEXT_PUBLIC_CHAIN=local
NEXT_PUBLIC_FIRST_BLOOD_CONTEST_ADDRESS_31337=$CONTEST_ADDRESS
NEXT_PUBLIC_VRF_COORDINATOR_ADDRESS_31337=$VRF_ADDRESS
EOL
echo -e "${GREEN}Created apps/web/.env.local${NC}"

# 4. Start VRF watcher
echo -e "\n${YELLOW}Starting VRF auto-fulfillment watcher...${NC}"
"$SCRIPT_DIR/vrf-watcher.sh" "$VRF_ADDRESS" > /tmp/vrf-watcher.log 2>&1 &
VRF_WATCHER_PID=$!
echo -e "${GREEN}VRF watcher started (PID: $VRF_WATCHER_PID)${NC}"

# 5. Start Next.js dev server
echo -e "\n${YELLOW}Starting Next.js dev server...${NC}"
cd apps/web
yarn dev > /tmp/next.log 2>&1 &
NEXT_PID=$!
cd "$PROJECT_ROOT"

# Wait for Next.js to start
sleep 3
echo -e "${GREEN}Next.js started (PID: $NEXT_PID)${NC}"

# Print summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Local environment ready!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "  Anvil:     http://localhost:8545"
echo "  Web:       http://localhost:3000"
echo "  VRF:       Auto-fulfilling requests"
echo ""
echo "  Contest:   $CONTEST_ADDRESS"
echo "  Contest ID: $CONTEST_ID"
echo ""
echo -e "${YELLOW}Test account (import to MetaMask):${NC}"
echo "  Address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
echo "  Key:     0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop${NC}"
echo ""

# Keep script running and show logs
tail -f /tmp/anvil.log /tmp/vrf-watcher.log /tmp/next.log 2>/dev/null || wait
